Euler_regression:
	python3 main.py -m Euler
NN_regression:
	python3 main.py -m NN -Nh 8 -Nn 20
	python3 main.py -m NN -Nh 4 -Nn 20
	python3 main.py -m NN -Nh 2 -Nn 20

all: Euler_regression NN_regression